RF07 Notebook + .yaml file
Smpljack/halo-flight-phase-separation pull request #3
Opened 2020-03-24 12:06 UTC by MaxRing96

2020-03-24 13:05 UTC, MaxRing96 commented
Updated RF07 Notebook and RF07_info.yaml file (two separate legs around wiggle-manoeuvre)

2020-03-24 14:08 UTC, marc-prange requested changes
Flight segments look good, also the straight leg / radar calibration issue is solved. 
But some flight segments name should be adjusted, see comment in yaml file.

2020-03-24 14:08 UTC, Smpljack commented on flight_phase_files/RF07_info.yaml
> +    name: radar_cal_tilted (10deg) around Ron Brown
Remove additional comment after "radar_cal_tilted". "tilted" is sufficiently specific here. Additional information is only required for the straight legs for now, e.g. "straight_leg_towards_ron_brown".

2020-03-25 11:14 UTC, MaxRing96 commented
Update RF07 Notebook and RF07_info.yaml (corrected segment names), and RF03 (new .to_yaml methode without dirname).

2020-03-25 11:16 UTC, Smpljack commented on flight_phase_files/RF07_info.yaml
> +  name: leg1
Specify leg more.

2020-03-25 11:17 UTC, Smpljack commented on flight_phase_files/RF07_info.yaml
> +  name: cb1
I suggest new convention for names of circle breaks. In this case: cb1to2

2020-03-25 11:20 UTC, marc-prange requested changes
Radar calibration formats are fine now. Still add specification on legs in name parameters. See flights of RF04 / RF05 for examples. I suggest a new format for circle break names, because by just indexing them (cb1, cb2, ...) it is unclear to which circles they relate (e.g. cb3 typically relates to c4 and c5, while c1 relates to c1 and c2).

2020-03-25 12:57 UTC, MaxRing96 commented
Updated the leg- and circlebreak-names.

2020-03-25 14:37 UTC, marc-prange approved these changes
Looks good!

2020-03-25 14:37 UTC, merged