update HALO-0126 to new definitions
Smpljack/halo-flight-phase-separation pull request #36
Opened 2020-06-12 01:33 UTC by Geet-George

2020-06-12 05:25 UTC, heikekonow commented
Hi Geet! I think you removed the file flight_phase_files/HALO_RF04_20200126_info.yaml in your last commit. Could you add it again?

2020-06-12 08:23 UTC, Geet-George commented
Sorry.. That was stupid. I wanted to remove the notebooks for RF03 and RF04, but I removed the YAML instead. The mistakes have been corrected.

2020-06-12 09:17 UTC, heikekonow requested changes

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126sc1
Segment ID should combine flight id with underscore: HALO-0126sc1 -> HALO-0126_sc1

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126sc1
```suggestion
  segment_id: HALO-0126_sc1
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126c1
```suggestion
  segment_id: HALO-0126_c1
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126cb1
```suggestion
  segment_id: HALO-0126_cb1
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126c2
```suggestion
  segment_id: HALO-0126_c2
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126cb2
```suggestion
  segment_id: HALO-0126_cb2
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126c3
```suggestion
  segment_id: HALO-0126_c3
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126o1
```suggestion
  segment_id: HALO-0126_o1
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126sl2
```suggestion
  segment_id: HALO-0126_sl2
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126sl3
```suggestion
  segment_id: HALO-0126_sl3
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126sl4
```suggestion
  segment_id: HALO-0126_sl4
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126rcw1
```suggestion
  segment_id: HALO-0126_rcw1
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126c4
```suggestion
  segment_id: HALO-0126_c4
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126cb3
```suggestion
  segment_id: HALO-0126_cb3
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126c5
```suggestion
  segment_id: HALO-0126_c5
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126cb4
```suggestion
  segment_id: HALO-0126_cb4
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126c6
```suggestion
  segment_id: HALO-0126_c6
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126o2
```suggestion
  segment_id: HALO-0126_o2
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126ll1
```suggestion
  segment_id: HALO-0126_ll1
```

2020-06-12 09:17 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  segment_id: HALO-0126sl1
```suggestion
  segment_id: HALO-0126_sl1
```

2020-06-12 09:18 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  - straight_leg
This segment should also be kind "super_curtain"
```suggestion
  - straight_leg
  - super_curtain
```

2020-06-12 09:26 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  tags:
There were some characters behind "tags:" that caused the reports scrip to provide an error message
```suggestion
  tags:
```

2020-06-12 09:28 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  end: 2020-01-26 13:22:28
Start and end overlap a bit; end circle two seconds earlier
```suggestion
  end: 2020-01-26 13:22:26
```

2020-06-12 09:29 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  start: 2020-01-26 13:22:29
Change start according to end of c1
```suggestion
  start: 2020-01-26 13:22:26
```

2020-06-12 09:30 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  end: 2020-01-26 15:39:13
This circle can be closed if it ends three seconds later
```suggestion
  end: 2020-01-26 15:39:16
```

2020-06-12 09:33 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  end: 2020-01-26 15:39:13
This circling period can be extended a bit in beginning and end for as long as HALO is on the circle pattern.
```suggestion
  start: 2020-01-26 12:24:06
  end: 2020-01-26 15:46:12
```

2020-06-12 09:33 UTC, Geet-George commented
For circle endings, are you looking at the zoomed-in plot? I went for the timestamp closest to a 360 degree completion, using the "Difference in heading" from the HTML that Tobi's report.py provided....

2020-06-12 09:36 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  end: 2020-01-26 18:18:34
This circle overlaps. The overlap can be reduced by ending the circle earlier.
```suggestion
  end: 2020-01-26 18:17:54
```

2020-06-12 09:38 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  end: 2020-01-26 18:18:34
This circle overlaps. The overlap can be reduced by ending the circle earlier.
```suggestion
  end: 2020-01-26 18:17:54
```

2020-06-12 09:38 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  start: 2020-01-26 18:18:35
If the end of c4 is changed, then the start of cb3 should be changed accordingly. 
```suggestion
  start: 2020-01-26 18:17:54
```

2020-06-12 09:43 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  end: 2020-01-26 13:34:10
End time of the circle break can be the same as the start time of the following circle, as we decided that the end is not part of the second (and vice versa).
```suggestion
  end: 2020-01-26 13:34:11
```

2020-06-12 09:43 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  start: 2020-01-26 14:30:32
```suggestion
  start: 2020-01-26 14:30:31
```

2020-06-12 09:43 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  end: 2020-01-26 14:42:24
```suggestion
  end: 2020-01-26 14:42:25
```

2020-06-12 09:48 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  name: Circle break between circle-5 and circle-6
End circle break with deviation due to traffic.
```suggestion
  name: Circle break between circle-5 and deviation due to traffic
```

2020-06-12 09:48 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  end: 2020-01-26 19:50:30
```suggestion
  start: 2020-01-26 19:33:16
  end: 2020-01-26 19:40:48
```
Change in start time is set to end of previous circle (I missed this one in the other comments)

2020-06-12 09:55 UTC, heikekonow reviewed
Tried to update o2 and create o3 to split the circling elements around the deviation due to traffic

2020-06-12 09:55 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  name: Circling phase 2 - Circle 4 to 6
```suggestion
  name: Circling phase 2 - Circle 4 to deviation due to traffic
```

2020-06-12 09:55 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +  end: 2020-01-26 20:47:00
```suggestion
  end: 2020-01-26 19:40:48
```

2020-06-12 09:55 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +    - HALO-0126_s75
These will be moved to new segment o3
```suggestion
```

2020-06-12 09:55 UTC, heikekonow commented on flight_phase_files/HALO_RF04_20200126_info.yaml
> +- kinds:
```suggestion
- kinds:
  - circling
  name: Circling phase 3 - Deviation due to traffic to circle 6
  irregularities:
  - between circle 5 and 6, the flight deviated from the circle due to a traffic issue
  segment_id: HALO-0126_o3
  start: 2020-01-26 19:51:19
  end: 2020-01-26 20:47:00
  dropsondes:
    GOOD:
    - HALO-0126_s64
    - HALO-0126_s65
    - HALO-0126_s66
    - HALO-0126_s67
    - HALO-0126_s68
    - HALO-0126_s69
    - HALO-0126_s70
    - HALO-0126_s71
    - HALO-0126_s72
    - HALO-0126_s73
    - HALO-0126_s74
    - HALO-0126_s75
    BAD: []
    UGLY: []
- kinds:
```

2020-06-12 09:57 UTC, heikekonow commented
Ok, I hope I filled in all my notes. 
Overall, this looks great. I have only a couple of minor comments and the deviation due to traffic as we discussed.
Thanks for the segmentation of this flight. That was a tricky one :-)

2020-06-12 09:59 UTC, heikekonow commented
> For circle endings, are you looking at the zoomed-in plot? I went for the timestamp closest to a 360 degree completion, using the "Difference in heading" from the HTML that Tobi's report.py provided....

Yes, I used the zoomed in plots. Going for difference in heading will probably also work. I'll leave the decision up to you.

2020-06-12 12:39 UTC, d70-t commented
> > For circle endings, are you looking at the zoomed-in plot? I went for the timestamp closest to a 360 degree completion, using the "Difference in heading" from the HTML that Tobi's report.py provided....
> 
> Yes, I used the zoomed in plots. Going for difference in heading will probably also work. I'll leave the decision up to you.

Note that heading will also change due to changes in wind speed and direction. So completing a circle does not necessarily mean returning to the same heading.

2020-06-12 15:05 UTC, Geet-George commented
But sticking to the rules (definition), shouldn't we go by least difference in heading? That was my thought process... I did see in the zoomed-in plots that doing so showed more or less overlap in the circle than we would like...

2020-06-13 10:52 UTC, d70-t commented
> But sticking to the rules (definition), shouldn't we go by least difference in heading? That was my thought process... I did see in the zoomed-in plots that doing so showed more or less overlap in the circle than we would like...

Hmm, I think I begin to see your point. In my head the idea of a 360° circle never has been 360° of heading change but 360° of rotation around the center of the circle and the heading being only a rough estimate for that number. Maybe our definition has been a bit unclear on that an we should figure that out?

2020-06-14 07:40 UTC, Geet-George commented
It was also rotation of 360° in my head, but I thought we use heading as the measurement to estimate that, and that's why I stuck to the definition, partly also because I thought marking circle completion at the return point closest to the start, will not be easy to define.

2020-06-14 13:26 UTC, Geet-George commented
Okay, since this idea of least heading difference is the odd one out, for convenience sake, I'll just change the times considering overlap of the circle. We can change the final definition accordingly later.

2020-06-14 23:41 UTC, Geet-George commented
Timestamps updated to minimise circle overlap, without considering heading differences. 

RF04 is now ready to merge.

2020-06-15 07:41 UTC, merged