Adding RF02 Notebook and RF02_info.yaml file.
Smpljack/halo-flight-phase-separation pull request #4
Opened 2020-03-30 16:00 UTC by MaxRing96

2020-03-31 15:48 UTC, Smpljack commented on flight_phase_files/RF02_info.yaml
> +- Basic pattern of circles, spur towards NTAS removed in lieu of calibration maneuvers.
in *favour* of calibration?

2020-03-31 15:50 UTC, marc-prange requested changes
Looks good, just one typo!

2020-04-01 10:23 UTC, MaxRing96 commented
Typo should be corrected!

2020-04-01 15:48 UTC, marc-prange approved these changes

2020-04-01 15:48 UTC, merged